services:
  web:
    build: .
    container_name: ccad-online-dashboard
    ports:
      - "5101:5101"
    volumes:
      - ./instance:/app/instance
      - ./uploads:/app/uploads
    shm_size: '256mb'
    command: ["sh", "-c", "python db_init.py && exec gunicorn --timeout 60 --log-level info -w 2 -b 0.0.0.0:5101 app:app"]
    restart: always
    env_file: .env
    environment:
      - FLASK_ENV=production
      - TZ=Asia/Dubai
